[package]
name = "index_arena"
version = "0.2.0"
authors = ["Yegor Vaskonyan <yegor.vaskonyan@gmail.com>"]
edition = "2021"
rust-version = "1.87.0"
description = "A simple, id-based, heterogeneous arena allocator"
repository = "https://github.com/yegorvk/index_arena"
license = "MIT OR Apache-2.0"
keywords = ["arena", "allocator"]
categories = ["memory-management", "rust-patterns"]

[features]
alloc = ["dep:aligned-vec"]

[dependencies]
derive-where = "1.6.0"
aligned-vec = { version = "0.6.4", optional = true }
